version: '3.4'
services:
  db:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5429:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb:/home/postgres/pgdata/data
    container_name: habanero_timescaledb
  server:
    build: .
    ports:
      - "5999:5999"
    env_file:
      - .env
    container_name: habanero_server

volumes:
  timescaledb:
